services:
  redis:
    image: redis:7-alpine
    container_name: genie_redis
    restart: always  
    volumes:
      - redis_data:/data 

  backend:
    build: .
    image: genie_backend_image
    container_name: genie_backend
    restart: always
    ports:
      - "8010:8010"
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0 
    depends_on:
      - redis
    volumes:
      - ./app/storage:/app/app/storage
      - ./app/logs:/app/app/logs 


  worker:
    image: genie_backend_image
    container_name: genie_worker
    restart: always
    command: celery -A app.workers.celery:celery_app worker --loglevel=info --concurrency=2
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./app/storage:/app/app/storage
      - ./app/logs:/app/app/logs 

  
volumes:
  redis_data: