"""add pdf and chunks tables

Revision ID: 40958a20f7db
Revises: 
Create Date: 2026-07-28 16:40:35.210568

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40958a20f7db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdfs',
    sa.Column('pdfid', sa.Integer(), nullable=False),
    sa.Column('pdfname', sa.String(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'CHUNKED', 'EMBEDDED', 'FAILED', name='status'), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pdfid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_pdfs_pdfid'), 'pdfs', ['pdfid'], unique=False)
    op.create_index(op.f('ix_pdfs_status'), 'pdfs', ['status'], unique=False)
    op.create_table('chunks',
    sa.Column('chunkid', sa.Integer(), nullable=False),
    sa.Column('pdfid', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'EMBEDDED', 'FAILED', name='chunkstatus'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pdfid'], ['pdfs.pdfid'], ),
    sa.PrimaryKeyConstraint('chunkid')
    )
    op.create_index(op.f('ix_chunks_chunkid'), 'chunks', ['chunkid'], unique=False)
    op.create_index(op.f('ix_chunks_pdfid'), 'chunks', ['pdfid'], unique=False)
    op.create_index(op.f('ix_chunks_status'), 'chunks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_status'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_pdfid'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_chunkid'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_pdfs_status'), table_name='pdfs')
    op.drop_index(op.f('ix_pdfs_pdfid'), table_name='pdfs')
    op.drop_table('pdfs')
    # ### end Alembic commands ###
