"""Unique constraint for (user, pdf_hash)

Revision ID: 8f4c566abe80
Revises: a7c41a68793e
Create Date: 2026-08-09 21:39:06.602368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4c566abe80'
down_revision: Union[str, Sequence[str], None] = 'a7c41a68793e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_pdfs_content_sha256'), 'pdfs', type_='unique')
    op.create_unique_constraint('unique_user_pdf_hash', 'pdfs', ['userid', 'content_sha256'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_pdf_hash', 'pdfs', type_='unique')
    op.create_unique_constraint(op.f('uq_pdfs_content_sha256'), 'pdfs', ['content_sha256'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
