"""add User table

Revision ID: a7c41a68793e
Revises: ea7f591e8a31
Create Date: 2026-08-01 13:57:36.278759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c41a68793e'
down_revision: Union[str, Sequence[str], None] = 'ea7f591e8a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index(op.f('ix_users_userid'), 'users', ['userid'], unique=False)
    op.add_column('pdfs', sa.Column('userid', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_pdfs_userid'), 'pdfs', ['userid'], unique=False)
    op.create_foreign_key(None, 'pdfs', 'users', ['userid'], ['userid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pdfs', type_='foreignkey')
    op.drop_index(op.f('ix_pdfs_userid'), table_name='pdfs')
    op.drop_column('pdfs', 'userid')
    op.drop_index(op.f('ix_users_userid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
