name: Deploy to AIC

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to AIC via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.AIC_SSH_KEY }}
          script: |
            cd PDF-Genie
            git pull origin main
            docker compose up --build -d
            docker image prune -f